import {
  LayoutDashboard,
  Users,
  UserCircle,
  Calendar,
  FileText,
  Pill,
  Package,
  ShoppingCart,
  Receipt,
  Database,
  BarChart3,
  Activity,
  Stethoscope,
  ClipboardList,
  Warehouse,
  Truck,
  FolderTree,
  MapPin,
  Building2,
  Ruler,
  Store,
  Grid,
  Briefcase,
  Heart,
  TrendingUp,
  Contact,
  Bot,
  Sparkles,
  Trophy,
  Award,
  UserPlus,
  Route,
  LineChart,
  BarChart2,
  BarChart,
  Target,
  Map,
  Home,
  Building,
  UserSearch,
  Handshake,
  GitBranch,
  CheckSquare,
  FileCheck,
  FileBarChart,
  UserCog,
  Shield,
  Settings,
  Factory,
  FileInput,
  Kanban,
  User2,
  Users2,
  Tag,
  PieChart,
  Settings2,
  Search,
} from "lucide-react";

// Export the icon map type for usage in other files
export type MenuIcon = keyof typeof iconMap;

const iconMap = {
  // Dashboard icons
  dashboard: <LayoutDashboard className="h-4 w-4" />,
  "layout-dashboard": <LayoutDashboard className="h-4 w-4" />,
  home: <Home className="h-4 w-4" />,
  
  // Data Master icons
  database: <Database className="h-4 w-4" />,
  building: <Building2 className="h-4 w-4" />,
  "building-2": <Building2 className="h-4 w-4" />,
  grid: <Grid className="h-4 w-4" />,
  briefcase: <Briefcase className="h-4 w-4" />,
  user: <UserCircle className="h-4 w-4" />,
  users: <Users className="h-4 w-4" />,
  heart: <Heart className="h-4 w-4" />,
  "user-plus": <UserPlus className="h-4 w-4" />,
  "master-data": <Database className="h-4 w-4" />,
  
  // Sales CRM icons
  "trending-up": <TrendingUp className="h-4 w-4" />,
  contact: <Contact className="h-4 w-4" />,
  route: <Route className="h-4 w-4" />,
  accounts: <Building className="h-4 w-4" />,
  leads: <UserSearch className="h-4 w-4" />,
  deals: <Handshake className="h-4 w-4" />,
  pipeline: <GitBranch className="h-4 w-4" />,
  products: <Package className="h-4 w-4" />,
  "sales-overview": <TrendingUp className="h-4 w-4" />,
  "sales-rep": <UserCog className="h-4 w-4" />,
  
  // Analytics icons
  "chart-line": <LineChart className="h-4 w-4" />,
  "chart-bar": <BarChart className="h-4 w-4" />,
  "bar-chart-2": <BarChart2 className="h-4 w-4" />,
  reports: <FileBarChart className="h-4 w-4" />,
  
  // Other icons
  calendar: <Calendar className="h-4 w-4" />,
  filetext: <FileText className="h-4 w-4" />,
  "file-text": <FileText className="h-4 w-4" />,
  pill: <Pill className="h-4 w-4" />,
  package: <Package className="h-4 w-4" />,
  shoppingcart: <ShoppingCart className="h-4 w-4" />,
  receipt: <Receipt className="h-4 w-4" />,
  barchart3: <BarChart3 className="h-4 w-4" />,
  "bar-chart-3": <BarChart3 className="h-4 w-4" />,
  activity: <Activity className="h-4 w-4" />,
  stethoscope: <Stethoscope className="h-4 w-4" />,
  clipboardlist: <ClipboardList className="h-4 w-4" />,
  warehouse: <Warehouse className="h-4 w-4" />,
  truck: <Truck className="h-4 w-4" />,
  foldertree: <FolderTree className="h-4 w-4" />,
  mappin: <MapPin className="h-4 w-4" />,
  ruler: <Ruler className="h-4 w-4" />,
  store: <Store className="h-4 w-4" />,
  "map-pin": <MapPin className="h-4 w-4" />,
  "clipboard-list": <ClipboardList className="h-4 w-4" />,
  bot: <Bot className="h-4 w-4" />,
  sparkles: <Sparkles className="h-4 w-4" />,
  "ai-chatbot": <Bot className="h-4 w-4" />,
  trophy: <Trophy className="h-4 w-4" />,
  award: <Award className="h-4 w-4" />,
  target: <Target className="h-4 w-4" />,
  map: <Map className="h-4 w-4" />,
  tasks: <CheckSquare className="h-4 w-4" />,
  "visit-reports": <FileCheck className="h-4 w-4" />,
  leaderboard: <Trophy className="h-4 w-4" />,
  profile: <UserCircle className="h-4 w-4" />,
  block: <Shield className="h-4 w-4" />,
  settings: <Settings className="h-4 w-4" />,
  factory: <Factory className="h-4 w-4" />,
  "file-input": <FileInput className="h-4 w-4" />,
  kanban: <Kanban className="h-4 w-4" />,
  "check-square": <CheckSquare className="h-4 w-4" />,
  "users-2": <Users2 className="h-4 w-4" />,
  "users-round": <Users className="h-4 w-4" />,
  tag: <Tag className="h-4 w-4" />,
  "pie-chart": <PieChart className="h-4 w-4" />,
  "file-bar-chart": <FileBarChart className="h-4 w-4" />,
  "settings-2": <Settings2 className="h-4 w-4" />,
  search: <Search className="h-4 w-4" />,
  shield: <Shield className="h-4 w-4" />,
};

export function getMenuIcon(iconName: string): React.ReactNode {
  return iconMap[iconName.toLowerCase() as MenuIcon] || <Database className="h-4 w-4" />;
}
